language: ruby
rvm:
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - 1.8.7
  - ree
  - 1.9.0
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - 2.0.0-p0
before_install:
- - sudo apt-get install rubygems build-essential
  - sudo gem install jekyll json less therubyracer
script: jeykll
notifications:
  irc: "irc.freenode.org#parttimelegend"
